# ROLL, ODD, EVEN

SOUTH_CENTRAL = [
[2, "MEMPHIS", "SHREVEPORT"],
[3, "MEMPHIS", "SHREVEPORT"],
[4, "MEMPHIS", "DALLAS"],
[5, "LITTLE ROCK", "NEW ORLEANS"],
[6, "NEW ORLEANS", "DALLAS"],
[7, "BIRMINGHAM", "SAN ANTONIO"],
[8, "LOUISVILLE", "HOUSTON"],
[9, "NASHVILLE", "HOUSTON"],
[10, "NASHVILLE", "FORT WORTH"],
[11, "LOUISVILLE", "FORT WORTH"],
[12, "MEMPHIS", "FORT WORTH"],
]

NORTHEAST = [
[2, "NEW YORK ", "NEW YORK "],
[3, "NEW YORK ", "WASHINGTON"],
[4, "NEW YORK ", "PITTSBURGH"],
[5, "ALBANY", "PITTSBURGH"],
[6, "BOSTON", "PHILADELPHIA"],
[7, "BUFFALO", "WASHINGTON"],
[8, "BOSTON", "PHILADELPHIA"],
[9, "PORTLAND", "BALTIMORE"],
[10, "NEW YORK ", "BALTIMORE"],
[11, "NEW YORK ", "BALTIMORE"],
[12, "NEW YORK ", "NEW YORK"],
]

PLAINS = [
[2, "KANSAS CITY", "OKLAHOMA CITY"],
[3, "KANSAS CITY", "ST PAUL"],
[4, "DENVER", "MINNEAPOLIS"],
[5, "DENVER", "ST PAUL"],
[6, "DENVER", "MINNEAPOLIS"],
[7, "KANSAS CITY", "OKLAHOMA CITY"],
[8, "KANSAS CITY", "DES MOINES"],
[9, "KANSAS CITY", "OMAHA"],
[10, "PUEBLO", "OMAHA"],
[11, "PUEBLO", "FARGO"],
[12, "OKLAHOMA CITY", "FARGO"],
]

SOUTHEAST = [
[2, "CHARLOTTE", "NORFOLK"],
[3, "CHARLOTTE", "NORFOLK"],
[4, "CHATTANOOGA", "NORFOLK"],
[5, "ATLANTA", "CHARLESTON"],
[6, "ATLANTA", "MIAMI"],
[7, "ATLANTA", "JACKSONVILLE"],
[8, "RICHMOND", "MIAMI"],
[9, "KNOXVILLE", "TAMPA"],
[10, "MOBILE", "TAMPA"],
[11, "KNOXVILLE", "MOBILE"],
[12, "MOBILE", "NORFOLK"],
]

NORTHWEST = [
[2, "SPOKANE", "SPOKANE"],
[3, "SPOKANE", "SALT LAKE CITY"],
[4, "SEATTLE", "SALT LAKE CITY"],
[5, "SEATTLE", "SALT LAKE CITY"],
[6, "SEATTLE", "PORTLAND"],
[7, "SEATTLE", "PORTLAND"],
[8, "RAPID CITY", "PORTLAND"],
[9, "CASPER", "POCATELLO"],
[10, "BILLINGS", "BUTTE"],
[11, "BILLINGS", "BUTTE"],
[12, "SPOKANE", "PORTLAND"],
]

NORTH_CENTRAL =[
[2, "CLEVELAND", "CINCINNATI"],
[3, "CLEVELAND", "CHICAGO"],
[4, "CLEVELAND", "CINCINNATI"],
[5, "CLEVELAND", "CINCINNATI"],
[6, "DETROIT", "COLUMBUS"],
[7, "DETROIT", "CHICAGO"],
[8, "INDIANAPOLIS", "CHICAGO"],
[9, "MILWAUKEE", "ST LOUIS"],
[10, "MILWAUKEE", "ST LOUIS"],
[11, "CHICAGO", "ST LOUIS" ],
[12, "MILWAUKEE", "CHICAGO"],
]

SOUTHWEST = [
[2, "SAN DIEGO", "LOS ANGELES"],
[3, "SAN DIEGO", "OAKLAND"],
[4, "RENO", "OAKLAND"],
[5, "SAN DIEGO", "OAKLAND"],
[6, "SACRAMENTO", "LOS ANGELES"],
[7, "LAS VEGAS", "LOS ANGELES"],
[8, "PHOENIX", "LOS ANGELES"],
[9, "EL PASO", "SAN FRANCISCO"],
[10, "TUCUMCARI", "SAN FRANCISCO"],
[11, "PHOENIX", "SAN FRANCISCO"],
[12, "PHOENIX", "SAN FRANCISCO"],
]

REGIONS_US_LIST = [SOUTH_CENTRAL, NORTHEAST, PLAINS, SOUTHEAST, NORTHWEST, NORTH_CENTRAL, SOUTHWEST]

REGIONS_US = [
[2, 'PLAINS', 'SOUTHWEST'],
[3, 'SOUTHEAST', 'SOUTH CENTRAL'],
[4, 'SOUTHEAST', 'SOUTH CENTRAL'],
[5, 'SOUTHEAST', 'SOUTH CENTRAL'],
[6, 'NORTH CENTRAL', 'SOUTHWEST'],
[7, 'NORTH CENTRAL', 'SOUTHWEST'],
[8, 'NORTHEAST', 'PLAINS'],
[9, 'NORTHEAST', 'NORTHWEST'],
[10, 'NORTHEAST', 'NORTHWEST'],
[11, 'SOUTHEAST', 'PLAINS'],
[12, 'NORTHEAST', 'NORTHWEST']
]

DESTINATIONS_US_DICT = {
    '2ODD': PLAINS,
    '2EVEN': SOUTHWEST,
    '3ODD': SOUTHEAST,
    '3EVEN': SOUTH_CENTRAL,
    '4ODD': SOUTHEAST,
    '4EVEN': SOUTH_CENTRAL,
    '5ODD': SOUTHEAST,
    '5EVEN': SOUTH_CENTRAL,
    '6ODD': NORTH_CENTRAL,
    '6EVEN': SOUTHWEST,
    '7ODD': NORTH_CENTRAL,
    '7EVEN': SOUTHWEST,
    '8ODD': NORTHEAST,
    '8EVEN': PLAINS,
    '9ODD': NORTHEAST,
    '9EVEN': NORTHWEST,
    '10ODD': NORTHEAST,
    '10EVEN': NORTHWEST,
    '11ODD': SOUTHEAST,
    '11EVEN': PLAINS,
    '12ODD': NORTHEAST,
    '12EVEN': NORTHWEST
}

REGIONS_RBUS = [
[2, 'PLAINS', 'SOUTHWEST'],
[3, 'SOUTHEAST', 'SOUTH CENTRAL'],
[4, 'SOUTHEAST', 'SOUTH CENTRAL'],
[5, 'SOUTHEAST', 'SOUTH CENTRAL'],
[6, 'NORTH CENTRAL', 'SOUTHWEST'],
[7, 'NORTH CENTRAL', 'SOUTHWEST'],
[8, 'NORTHEAST', 'PLAINS'],
[9, 'NORTHEAST', 'NORTHWEST'],
[10, 'NORTHEAST', 'NORTHWEST'],
[11, 'NORTHEAST', 'PLAINS'],
[12, 'NORTHEAST', 'NORTHWEST']
]

DESTINATIONS_RBUS_DICT = {
    '2ODD': PLAINS,
    '2EVEN': SOUTHWEST,
    '3ODD': SOUTHEAST,
    '3EVEN': SOUTH_CENTRAL,
    '4ODD': SOUTHEAST,
    '4EVEN': SOUTH_CENTRAL,
    '5ODD': SOUTHEAST,
    '5EVEN': SOUTH_CENTRAL,
    '6ODD': NORTH_CENTRAL,
    '6EVEN': SOUTHWEST,
    '7ODD': NORTH_CENTRAL,
    '7EVEN': SOUTHWEST,
    '8ODD': NORTHEAST,
    '8EVEN': PLAINS,
    '9ODD': NORTHEAST,
    '9EVEN': NORTHWEST,
    '10ODD': NORTHEAST,
    '10EVEN': NORTHWEST,
    '11ODD': NORTHEAST,
    '11EVEN': PLAINS,
    '12ODD': NORTHEAST,
    '12EVEN': NORTHWEST
}